openapi: '3.1.0'
info:
  title: TRXd
  version: '1.0'
servers:
  - url: http://127.0.0.1/api/

paths:
  /register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "./types.yml#/components/schemas/user_name"
                email:
                  $ref: "./types.yml#/components/schemas/email"
                password:
                  $ref: "./types.yml#/components/schemas/password"
              required: [name, email, password]
      responses:
        "200":
          description: OK
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "./errors.yml#/components/schemas/ErrorResponse"
        "409":
          description: "Conflict"
          content:
            application/json:
              schema:
                $ref: "./errors.yml#/components/schemas/ErrorResponse"